---
name: Checks

on: [push, pull-request]

jobs:
  build:
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: myapp_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with: bundle-cache: true

      - name: Database setup
        run: |
          rails db:setup RAILS_ENV=test

      - name: Run RSpec tests
        run: |
          rspec

      - name: Run RuboCop
        run: |
          rubocop
